# Generated by Django 5.0.1 on 2024-04-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hibatipusok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiba', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Megrendelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('cim', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefon', models.IntegerField()),
                ('rendszam', models.CharField(max_length=10)),
                ('gyartmany', models.CharField(max_length=255)),
                ('tipus', models.CharField(max_length=255)),
                ('gyartasi_ev', models.IntegerField()),
                ('alvazszam', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Munkalap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('utolsomodositas', models.DateTimeField(auto_now=True)),
                ('munkalapstatus', models.CharField(choices=[('enum_value_1', 'Aktív'), ('enum_value_2', 'Lezárt')], default='Aktív', max_length=20)),
                ('munkalapszam', models.CharField(max_length=20, unique=True)),
                ('kmoraallas', models.IntegerField()),
                ('uzemenyagszint', models.CharField(choices=[('enum_value_1', 'Negyed'), ('enum_value_2', 'Fél'), ('enum_value_3', 'Háromnegyed'), ('enum_value_4', 'Tele')], max_length=20)),
                ('hibaleiras', models.TextField()),
                ('varhatohatarido', models.DateField()),
                ('elvegzettmunka', models.TextField(blank=True)),
                ('felhasznaltanyag', models.TextField(blank=True)),
                ('hibatipus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymunkalap_app.hibatipusok')),
                ('megrendelo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymunkalap_app.megrendelo')),
            ],
        ),
    ]
