# Generated by Django 5.0.1 on 2024-02-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymunkalap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munkalap',
            name='munkalapstatus',
            field=models.CharField(choices=[('enum_value_1', 'Aktív'), ('enum_value_2', 'Lezárt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='munkalap',
            name='uzemenyagszint',
            field=models.CharField(choices=[('enum_value_1', 'Negyed'), ('enum_value_2', 'Fél'), ('enum_value_3', 'Háromnegyed'), ('enum_value_4', 'Tele')], max_length=20),
        ),
    ]
