# Generated by Django 5.0.1 on 2024-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymunkalap_app', '0002_alter_munkalap_munkalapstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munkalap',
            name='elvegzettmunka',
            field=models.TextField(null=True),
        ),
    ]
