# Generated by Django 5.0.1 on 2024-02-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymunkalap_app', '0003_alter_munkalap_elvegzettmunka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munkalap',
            name='felhasznaltanyag',
            field=models.TextField(null=True),
        ),
    ]
