# Generated by Django 5.0.1 on 2024-02-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymunkalap_app', '0005_alter_munkalap_munkalapstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munkalap',
            name='elvegzettmunka',
            field=models.TextField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='munkalap',
            name='felhasznaltanyag',
            field=models.TextField(blank=True, default=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='munkalap',
            name='munkalapszam',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
