# Generated by Django 5.0.1 on 2024-02-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymunkalap_app', '0006_alter_munkalap_elvegzettmunka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munkalap',
            name='datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='munkalap',
            name='utolsomodositas',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
