# Generated by Django 5.0.1 on 2024-04-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymunkalap_app', '0007_alter_munkalap_datum_alter_munkalap_utolsomodositas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megrendelo',
            name='gepjarmu_ID',
        ),
        migrations.AddField(
            model_name='gepjarmu',
            name='megrendelo_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mymunkalap_app.megrendelo'),
            preserve_default=False,
        ),
    ]
