# Generated by Django 5.0.1 on 2024-04-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymunkalap_app', '0008_remove_megrendelo_gepjarmu_id_gepjarmu_megrendelo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='munkalap',
            name='gepjarmu_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mymunkalap_app.gepjarmu'),
            preserve_default=False,
        ),
    ]
